[build.env]
volumes = [
    ".git=.git"
]
passthrough = [
  "VERGEN_IDEMPOTENT",
  "VERGEN_GIT_BRANCH",
  "VERGEN_GIT_SHA",
  "VERGEN_GIT_COMMIT_TIMESTAMP",
  "VERGEN_GIT_DESCRIBE",
  "VERGEN_GIT_DIRTY",
  "VERGEN_GIT_COMMIT_AUTHOR_EMAIL",
  "VERGEN_GIT_COMMIT_AUTHOR_NAME",
  "VERGEN_GIT_COMMIT_COUNT",
  "VERGEN_GIT_COMMIT_DATE",
  "VERGEN_GIT_COMMIT_MESSAGE"
]
