version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  bunshot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      # RabbitMQ
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
      - RABBITMQ_QUEUE=screenshots
      # AWS S3 (replace with your actual values)
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      # Screenshot settings
      - SCREENSHOT_WIDTH=1920
      - SCREENSHOT_HEIGHT=1080
      - SCREENSHOT_QUALITY=80
      - SCREENSHOT_TIMEOUT=30000
    restart: unless-stopped

volumes:
  rabbitmq_data: 