/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DebugImport } from './routes/debug'
import { Route as BootstrapImport } from './routes/bootstrap'
import { Route as AuthedImport } from './routes/_authed'
import { Route as AuthedIndexImport } from './routes/_authed/index'
import { Route as InviteInviteIdIndexImport } from './routes/invite/$inviteId/index'
import { Route as AuthedTeamNewImport } from './routes/_authed/team/new'
import { Route as AuthedSiteNewImport } from './routes/_authed/site/new'
import { Route as AuthedSettingsSImport } from './routes/_authed/settings/_s'
import { Route as AuthedAdminAImport } from './routes/_authed/admin/_a'
import { Route as AuthedTeamTeamIdIndexImport } from './routes/_authed/team/$teamId/index'
import { Route as AuthedSettingsSIndexImport } from './routes/_authed/settings/_s.index'
import { Route as AuthedAdminAIndexImport } from './routes/_authed/admin/_a/index'
import { Route as AuthedTeamTeamIdSitesImport } from './routes/_authed/team/$teamId/sites'
import { Route as AuthedSiteSiteIdSiteImport } from './routes/_authed/site/$siteId._site'
import { Route as AuthedSiteSiteIdSiteIndexImport } from './routes/_authed/site/$siteId._site/index'
import { Route as AuthedTeamTeamIdSettingsSImport } from './routes/_authed/team/$teamId/settings/_s'
import { Route as AuthedSiteSiteIdSiteDeploymentsImport } from './routes/_authed/site/$siteId._site/deployments'
import { Route as AuthedSiteSiteIdSiteAnalyticsImport } from './routes/_authed/site/$siteId._site/analytics'
import { Route as AuthedTeamTeamIdSettingsSIndexImport } from './routes/_authed/team/$teamId/settings/_s.index'
import { Route as AuthedTeamTeamIdSettingsSWebhooksImport } from './routes/_authed/team/$teamId/settings/_s.webhooks'
import { Route as AuthedTeamTeamIdSettingsSTransferImport } from './routes/_authed/team/$teamId/settings/_s.transfer'
import { Route as AuthedTeamTeamIdSettingsSMembersImport } from './routes/_authed/team/$teamId/settings/_s.members'
import { Route as AuthedTeamTeamIdSettingsSKeysImport } from './routes/_authed/team/$teamId/settings/_s.keys'
import { Route as AuthedTeamTeamIdSettingsSCiImport } from './routes/_authed/team/$teamId/settings/_s.ci'
import { Route as AuthedTeamTeamIdSettingsSActionsImport } from './routes/_authed/team/$teamId/settings/_s.actions'
import { Route as AuthedSiteSiteIdSiteSettingsSImport } from './routes/_authed/site/$siteId._site/settings/_s'
import { Route as AuthedSiteSiteIdSiteSettingsSIndexImport } from './routes/_authed/site/$siteId._site/settings/_s.index'
import { Route as AuthedSiteSiteIdSiteDeploymentDeploymentIdIndexImport } from './routes/_authed/site/$siteId._site/deployment/$deploymentId/index'
import { Route as AuthedSiteSiteIdSiteSettingsSWebhooksImport } from './routes/_authed/site/$siteId._site/settings/_s.webhooks'
import { Route as AuthedSiteSiteIdSiteSettingsSTransferImport } from './routes/_authed/site/$siteId._site/settings/_s.transfer'
import { Route as AuthedSiteSiteIdSiteSettingsSRulesImport } from './routes/_authed/site/$siteId._site/settings/_s.rules'
import { Route as AuthedSiteSiteIdSiteSettingsSKeysImport } from './routes/_authed/site/$siteId._site/settings/_s.keys'
import { Route as AuthedSiteSiteIdSiteSettingsSIpfsImport } from './routes/_authed/site/$siteId._site/settings/_s.ipfs'
import { Route as AuthedSiteSiteIdSiteSettingsSDomainsImport } from './routes/_authed/site/$siteId._site/settings/_s.domains'
import { Route as AuthedSiteSiteIdSiteSettingsSCiImport } from './routes/_authed/site/$siteId._site/settings/_s.ci'
import { Route as AuthedSiteSiteIdSiteSettingsSActionsImport } from './routes/_authed/site/$siteId._site/settings/_s.actions'

// Create Virtual Routes

const AuthedSettingsImport = createFileRoute('/_authed/settings')()
const AuthedAdminImport = createFileRoute('/_authed/admin')()
const AuthedSiteSiteIdImport = createFileRoute('/_authed/site/$siteId')()
const AuthedTeamTeamIdSettingsImport = createFileRoute(
  '/_authed/team/$teamId/settings',
)()
const AuthedSiteSiteIdSiteSettingsImport = createFileRoute(
  '/_authed/site/$siteId/_site/settings',
)()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DebugRoute = DebugImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRoute,
} as any)

const BootstrapRoute = BootstrapImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const AuthedSettingsRoute = AuthedSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedAdminRoute = AuthedAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedIndexRoute = AuthedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedSiteSiteIdRoute = AuthedSiteSiteIdImport.update({
  id: '/site/$siteId',
  path: '/site/$siteId',
  getParentRoute: () => AuthedRoute,
} as any)

const InviteInviteIdIndexRoute = InviteInviteIdIndexImport.update({
  id: '/invite/$inviteId/',
  path: '/invite/$inviteId/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedTeamNewRoute = AuthedTeamNewImport.update({
  id: '/team/new',
  path: '/team/new',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedSiteNewRoute = AuthedSiteNewImport.update({
  id: '/site/new',
  path: '/site/new',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedSettingsSRoute = AuthedSettingsSImport.update({
  id: '/_s',
  getParentRoute: () => AuthedSettingsRoute,
} as any)

const AuthedAdminARoute = AuthedAdminAImport.update({
  id: '/_a',
  getParentRoute: () => AuthedAdminRoute,
} as any)

const AuthedTeamTeamIdSettingsRoute = AuthedTeamTeamIdSettingsImport.update({
  id: '/team/$teamId/settings',
  path: '/team/$teamId/settings',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedTeamTeamIdIndexRoute = AuthedTeamTeamIdIndexImport.update({
  id: '/team/$teamId/',
  path: '/team/$teamId/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedSettingsSIndexRoute = AuthedSettingsSIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsSRoute,
} as any)

const AuthedAdminAIndexRoute = AuthedAdminAIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminARoute,
} as any)

const AuthedTeamTeamIdSitesRoute = AuthedTeamTeamIdSitesImport.update({
  id: '/team/$teamId/sites',
  path: '/team/$teamId/sites',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedSiteSiteIdSiteRoute = AuthedSiteSiteIdSiteImport.update({
  id: '/_site',
  getParentRoute: () => AuthedSiteSiteIdRoute,
} as any)

const AuthedSiteSiteIdSiteSettingsRoute =
  AuthedSiteSiteIdSiteSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedSiteSiteIdSiteRoute,
  } as any)

const AuthedSiteSiteIdSiteIndexRoute = AuthedSiteSiteIdSiteIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSiteSiteIdSiteRoute,
} as any)

const AuthedTeamTeamIdSettingsSRoute = AuthedTeamTeamIdSettingsSImport.update({
  id: '/_s',
  getParentRoute: () => AuthedTeamTeamIdSettingsRoute,
} as any)

const AuthedSiteSiteIdSiteDeploymentsRoute =
  AuthedSiteSiteIdSiteDeploymentsImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthedSiteSiteIdSiteRoute,
  } as any)

const AuthedSiteSiteIdSiteAnalyticsRoute =
  AuthedSiteSiteIdSiteAnalyticsImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthedSiteSiteIdSiteRoute,
  } as any)

const AuthedTeamTeamIdSettingsSIndexRoute =
  AuthedTeamTeamIdSettingsSIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedTeamTeamIdSettingsSRoute,
  } as any)

const AuthedTeamTeamIdSettingsSWebhooksRoute =
  AuthedTeamTeamIdSettingsSWebhooksImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthedTeamTeamIdSettingsSRoute,
  } as any)

const AuthedTeamTeamIdSettingsSTransferRoute =
  AuthedTeamTeamIdSettingsSTransferImport.update({
    id: '/transfer',
    path: '/transfer',
    getParentRoute: () => AuthedTeamTeamIdSettingsSRoute,
  } as any)

const AuthedTeamTeamIdSettingsSMembersRoute =
  AuthedTeamTeamIdSettingsSMembersImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthedTeamTeamIdSettingsSRoute,
  } as any)

const AuthedTeamTeamIdSettingsSKeysRoute =
  AuthedTeamTeamIdSettingsSKeysImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => AuthedTeamTeamIdSettingsSRoute,
  } as any)

const AuthedTeamTeamIdSettingsSCiRoute =
  AuthedTeamTeamIdSettingsSCiImport.update({
    id: '/ci',
    path: '/ci',
    getParentRoute: () => AuthedTeamTeamIdSettingsSRoute,
  } as any)

const AuthedTeamTeamIdSettingsSActionsRoute =
  AuthedTeamTeamIdSettingsSActionsImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => AuthedTeamTeamIdSettingsSRoute,
  } as any)

const AuthedSiteSiteIdSiteSettingsSRoute =
  AuthedSiteSiteIdSiteSettingsSImport.update({
    id: '/_s',
    getParentRoute: () => AuthedSiteSiteIdSiteSettingsRoute,
  } as any)

const AuthedSiteSiteIdSiteSettingsSIndexRoute =
  AuthedSiteSiteIdSiteSettingsSIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedSiteSiteIdSiteSettingsSRoute,
  } as any)

const AuthedSiteSiteIdSiteDeploymentDeploymentIdIndexRoute =
  AuthedSiteSiteIdSiteDeploymentDeploymentIdIndexImport.update({
    id: '/deployment/$deploymentId/',
    path: '/deployment/$deploymentId/',
    getParentRoute: () => AuthedSiteSiteIdSiteRoute,
  } as any)

const AuthedSiteSiteIdSiteSettingsSWebhooksRoute =
  AuthedSiteSiteIdSiteSettingsSWebhooksImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthedSiteSiteIdSiteSettingsSRoute,
  } as any)

const AuthedSiteSiteIdSiteSettingsSTransferRoute =
  AuthedSiteSiteIdSiteSettingsSTransferImport.update({
    id: '/transfer',
    path: '/transfer',
    getParentRoute: () => AuthedSiteSiteIdSiteSettingsSRoute,
  } as any)

const AuthedSiteSiteIdSiteSettingsSRulesRoute =
  AuthedSiteSiteIdSiteSettingsSRulesImport.update({
    id: '/rules',
    path: '/rules',
    getParentRoute: () => AuthedSiteSiteIdSiteSettingsSRoute,
  } as any)

const AuthedSiteSiteIdSiteSettingsSKeysRoute =
  AuthedSiteSiteIdSiteSettingsSKeysImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => AuthedSiteSiteIdSiteSettingsSRoute,
  } as any)

const AuthedSiteSiteIdSiteSettingsSIpfsRoute =
  AuthedSiteSiteIdSiteSettingsSIpfsImport.update({
    id: '/ipfs',
    path: '/ipfs',
    getParentRoute: () => AuthedSiteSiteIdSiteSettingsSRoute,
  } as any)

const AuthedSiteSiteIdSiteSettingsSDomainsRoute =
  AuthedSiteSiteIdSiteSettingsSDomainsImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AuthedSiteSiteIdSiteSettingsSRoute,
  } as any)

const AuthedSiteSiteIdSiteSettingsSCiRoute =
  AuthedSiteSiteIdSiteSettingsSCiImport.update({
    id: '/ci',
    path: '/ci',
    getParentRoute: () => AuthedSiteSiteIdSiteSettingsSRoute,
  } as any)

const AuthedSiteSiteIdSiteSettingsSActionsRoute =
  AuthedSiteSiteIdSiteSettingsSActionsImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => AuthedSiteSiteIdSiteSettingsSRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapImport
      parentRoute: typeof rootRoute
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/admin/_a': {
      id: '/_authed/admin/_a'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminAImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/settings/_s': {
      id: '/_authed/settings/_s'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsSImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/site/new': {
      id: '/_authed/site/new'
      path: '/site/new'
      fullPath: '/site/new'
      preLoaderRoute: typeof AuthedSiteNewImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/team/new': {
      id: '/_authed/team/new'
      path: '/team/new'
      fullPath: '/team/new'
      preLoaderRoute: typeof AuthedTeamNewImport
      parentRoute: typeof AuthedImport
    }
    '/invite/$inviteId/': {
      id: '/invite/$inviteId/'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof InviteInviteIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed/site/$siteId': {
      id: '/_authed/site/$siteId'
      path: '/site/$siteId'
      fullPath: '/site/$siteId'
      preLoaderRoute: typeof AuthedSiteSiteIdImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/site/$siteId/_site': {
      id: '/_authed/site/$siteId/_site'
      path: '/site/$siteId'
      fullPath: '/site/$siteId'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteImport
      parentRoute: typeof AuthedSiteSiteIdRoute
    }
    '/_authed/team/$teamId/sites': {
      id: '/_authed/team/$teamId/sites'
      path: '/team/$teamId/sites'
      fullPath: '/team/$teamId/sites'
      preLoaderRoute: typeof AuthedTeamTeamIdSitesImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/admin/_a/': {
      id: '/_authed/admin/_a/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminAIndexImport
      parentRoute: typeof AuthedAdminAImport
    }
    '/_authed/settings/_s/': {
      id: '/_authed/settings/_s/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsSIndexImport
      parentRoute: typeof AuthedSettingsSImport
    }
    '/_authed/team/$teamId/': {
      id: '/_authed/team/$teamId/'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof AuthedTeamTeamIdIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/site/$siteId/_site/analytics': {
      id: '/_authed/site/$siteId/_site/analytics'
      path: '/analytics'
      fullPath: '/site/$siteId/analytics'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteAnalyticsImport
      parentRoute: typeof AuthedSiteSiteIdSiteImport
    }
    '/_authed/site/$siteId/_site/deployments': {
      id: '/_authed/site/$siteId/_site/deployments'
      path: '/deployments'
      fullPath: '/site/$siteId/deployments'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteDeploymentsImport
      parentRoute: typeof AuthedSiteSiteIdSiteImport
    }
    '/_authed/team/$teamId/settings': {
      id: '/_authed/team/$teamId/settings'
      path: '/team/$teamId/settings'
      fullPath: '/team/$teamId/settings'
      preLoaderRoute: typeof AuthedTeamTeamIdSettingsImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/team/$teamId/settings/_s': {
      id: '/_authed/team/$teamId/settings/_s'
      path: '/team/$teamId/settings'
      fullPath: '/team/$teamId/settings'
      preLoaderRoute: typeof AuthedTeamTeamIdSettingsSImport
      parentRoute: typeof AuthedTeamTeamIdSettingsRoute
    }
    '/_authed/site/$siteId/_site/': {
      id: '/_authed/site/$siteId/_site/'
      path: '/'
      fullPath: '/site/$siteId/'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteIndexImport
      parentRoute: typeof AuthedSiteSiteIdSiteImport
    }
    '/_authed/site/$siteId/_site/settings': {
      id: '/_authed/site/$siteId/_site/settings'
      path: '/settings'
      fullPath: '/site/$siteId/settings'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteSettingsImport
      parentRoute: typeof AuthedSiteSiteIdSiteImport
    }
    '/_authed/site/$siteId/_site/settings/_s': {
      id: '/_authed/site/$siteId/_site/settings/_s'
      path: '/settings'
      fullPath: '/site/$siteId/settings'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteSettingsSImport
      parentRoute: typeof AuthedSiteSiteIdSiteSettingsRoute
    }
    '/_authed/team/$teamId/settings/_s/actions': {
      id: '/_authed/team/$teamId/settings/_s/actions'
      path: '/actions'
      fullPath: '/team/$teamId/settings/actions'
      preLoaderRoute: typeof AuthedTeamTeamIdSettingsSActionsImport
      parentRoute: typeof AuthedTeamTeamIdSettingsSImport
    }
    '/_authed/team/$teamId/settings/_s/ci': {
      id: '/_authed/team/$teamId/settings/_s/ci'
      path: '/ci'
      fullPath: '/team/$teamId/settings/ci'
      preLoaderRoute: typeof AuthedTeamTeamIdSettingsSCiImport
      parentRoute: typeof AuthedTeamTeamIdSettingsSImport
    }
    '/_authed/team/$teamId/settings/_s/keys': {
      id: '/_authed/team/$teamId/settings/_s/keys'
      path: '/keys'
      fullPath: '/team/$teamId/settings/keys'
      preLoaderRoute: typeof AuthedTeamTeamIdSettingsSKeysImport
      parentRoute: typeof AuthedTeamTeamIdSettingsSImport
    }
    '/_authed/team/$teamId/settings/_s/members': {
      id: '/_authed/team/$teamId/settings/_s/members'
      path: '/members'
      fullPath: '/team/$teamId/settings/members'
      preLoaderRoute: typeof AuthedTeamTeamIdSettingsSMembersImport
      parentRoute: typeof AuthedTeamTeamIdSettingsSImport
    }
    '/_authed/team/$teamId/settings/_s/transfer': {
      id: '/_authed/team/$teamId/settings/_s/transfer'
      path: '/transfer'
      fullPath: '/team/$teamId/settings/transfer'
      preLoaderRoute: typeof AuthedTeamTeamIdSettingsSTransferImport
      parentRoute: typeof AuthedTeamTeamIdSettingsSImport
    }
    '/_authed/team/$teamId/settings/_s/webhooks': {
      id: '/_authed/team/$teamId/settings/_s/webhooks'
      path: '/webhooks'
      fullPath: '/team/$teamId/settings/webhooks'
      preLoaderRoute: typeof AuthedTeamTeamIdSettingsSWebhooksImport
      parentRoute: typeof AuthedTeamTeamIdSettingsSImport
    }
    '/_authed/team/$teamId/settings/_s/': {
      id: '/_authed/team/$teamId/settings/_s/'
      path: '/'
      fullPath: '/team/$teamId/settings/'
      preLoaderRoute: typeof AuthedTeamTeamIdSettingsSIndexImport
      parentRoute: typeof AuthedTeamTeamIdSettingsSImport
    }
    '/_authed/site/$siteId/_site/settings/_s/actions': {
      id: '/_authed/site/$siteId/_site/settings/_s/actions'
      path: '/actions'
      fullPath: '/site/$siteId/settings/actions'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteSettingsSActionsImport
      parentRoute: typeof AuthedSiteSiteIdSiteSettingsSImport
    }
    '/_authed/site/$siteId/_site/settings/_s/ci': {
      id: '/_authed/site/$siteId/_site/settings/_s/ci'
      path: '/ci'
      fullPath: '/site/$siteId/settings/ci'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteSettingsSCiImport
      parentRoute: typeof AuthedSiteSiteIdSiteSettingsSImport
    }
    '/_authed/site/$siteId/_site/settings/_s/domains': {
      id: '/_authed/site/$siteId/_site/settings/_s/domains'
      path: '/domains'
      fullPath: '/site/$siteId/settings/domains'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteSettingsSDomainsImport
      parentRoute: typeof AuthedSiteSiteIdSiteSettingsSImport
    }
    '/_authed/site/$siteId/_site/settings/_s/ipfs': {
      id: '/_authed/site/$siteId/_site/settings/_s/ipfs'
      path: '/ipfs'
      fullPath: '/site/$siteId/settings/ipfs'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteSettingsSIpfsImport
      parentRoute: typeof AuthedSiteSiteIdSiteSettingsSImport
    }
    '/_authed/site/$siteId/_site/settings/_s/keys': {
      id: '/_authed/site/$siteId/_site/settings/_s/keys'
      path: '/keys'
      fullPath: '/site/$siteId/settings/keys'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteSettingsSKeysImport
      parentRoute: typeof AuthedSiteSiteIdSiteSettingsSImport
    }
    '/_authed/site/$siteId/_site/settings/_s/rules': {
      id: '/_authed/site/$siteId/_site/settings/_s/rules'
      path: '/rules'
      fullPath: '/site/$siteId/settings/rules'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteSettingsSRulesImport
      parentRoute: typeof AuthedSiteSiteIdSiteSettingsSImport
    }
    '/_authed/site/$siteId/_site/settings/_s/transfer': {
      id: '/_authed/site/$siteId/_site/settings/_s/transfer'
      path: '/transfer'
      fullPath: '/site/$siteId/settings/transfer'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteSettingsSTransferImport
      parentRoute: typeof AuthedSiteSiteIdSiteSettingsSImport
    }
    '/_authed/site/$siteId/_site/settings/_s/webhooks': {
      id: '/_authed/site/$siteId/_site/settings/_s/webhooks'
      path: '/webhooks'
      fullPath: '/site/$siteId/settings/webhooks'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteSettingsSWebhooksImport
      parentRoute: typeof AuthedSiteSiteIdSiteSettingsSImport
    }
    '/_authed/site/$siteId/_site/deployment/$deploymentId/': {
      id: '/_authed/site/$siteId/_site/deployment/$deploymentId/'
      path: '/deployment/$deploymentId'
      fullPath: '/site/$siteId/deployment/$deploymentId'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteDeploymentDeploymentIdIndexImport
      parentRoute: typeof AuthedSiteSiteIdSiteImport
    }
    '/_authed/site/$siteId/_site/settings/_s/': {
      id: '/_authed/site/$siteId/_site/settings/_s/'
      path: '/'
      fullPath: '/site/$siteId/settings/'
      preLoaderRoute: typeof AuthedSiteSiteIdSiteSettingsSIndexImport
      parentRoute: typeof AuthedSiteSiteIdSiteSettingsSImport
    }
  }
}

// Create and export the route tree

interface AuthedAdminARouteChildren {
  AuthedAdminAIndexRoute: typeof AuthedAdminAIndexRoute
}

const AuthedAdminARouteChildren: AuthedAdminARouteChildren = {
  AuthedAdminAIndexRoute: AuthedAdminAIndexRoute,
}

const AuthedAdminARouteWithChildren = AuthedAdminARoute._addFileChildren(
  AuthedAdminARouteChildren,
)

interface AuthedAdminRouteChildren {
  AuthedAdminARoute: typeof AuthedAdminARouteWithChildren
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminARoute: AuthedAdminARouteWithChildren,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedSettingsSRouteChildren {
  AuthedSettingsSIndexRoute: typeof AuthedSettingsSIndexRoute
}

const AuthedSettingsSRouteChildren: AuthedSettingsSRouteChildren = {
  AuthedSettingsSIndexRoute: AuthedSettingsSIndexRoute,
}

const AuthedSettingsSRouteWithChildren = AuthedSettingsSRoute._addFileChildren(
  AuthedSettingsSRouteChildren,
)

interface AuthedSettingsRouteChildren {
  AuthedSettingsSRoute: typeof AuthedSettingsSRouteWithChildren
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsSRoute: AuthedSettingsSRouteWithChildren,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedSiteSiteIdSiteSettingsSRouteChildren {
  AuthedSiteSiteIdSiteSettingsSActionsRoute: typeof AuthedSiteSiteIdSiteSettingsSActionsRoute
  AuthedSiteSiteIdSiteSettingsSCiRoute: typeof AuthedSiteSiteIdSiteSettingsSCiRoute
  AuthedSiteSiteIdSiteSettingsSDomainsRoute: typeof AuthedSiteSiteIdSiteSettingsSDomainsRoute
  AuthedSiteSiteIdSiteSettingsSIpfsRoute: typeof AuthedSiteSiteIdSiteSettingsSIpfsRoute
  AuthedSiteSiteIdSiteSettingsSKeysRoute: typeof AuthedSiteSiteIdSiteSettingsSKeysRoute
  AuthedSiteSiteIdSiteSettingsSRulesRoute: typeof AuthedSiteSiteIdSiteSettingsSRulesRoute
  AuthedSiteSiteIdSiteSettingsSTransferRoute: typeof AuthedSiteSiteIdSiteSettingsSTransferRoute
  AuthedSiteSiteIdSiteSettingsSWebhooksRoute: typeof AuthedSiteSiteIdSiteSettingsSWebhooksRoute
  AuthedSiteSiteIdSiteSettingsSIndexRoute: typeof AuthedSiteSiteIdSiteSettingsSIndexRoute
}

const AuthedSiteSiteIdSiteSettingsSRouteChildren: AuthedSiteSiteIdSiteSettingsSRouteChildren =
  {
    AuthedSiteSiteIdSiteSettingsSActionsRoute:
      AuthedSiteSiteIdSiteSettingsSActionsRoute,
    AuthedSiteSiteIdSiteSettingsSCiRoute: AuthedSiteSiteIdSiteSettingsSCiRoute,
    AuthedSiteSiteIdSiteSettingsSDomainsRoute:
      AuthedSiteSiteIdSiteSettingsSDomainsRoute,
    AuthedSiteSiteIdSiteSettingsSIpfsRoute:
      AuthedSiteSiteIdSiteSettingsSIpfsRoute,
    AuthedSiteSiteIdSiteSettingsSKeysRoute:
      AuthedSiteSiteIdSiteSettingsSKeysRoute,
    AuthedSiteSiteIdSiteSettingsSRulesRoute:
      AuthedSiteSiteIdSiteSettingsSRulesRoute,
    AuthedSiteSiteIdSiteSettingsSTransferRoute:
      AuthedSiteSiteIdSiteSettingsSTransferRoute,
    AuthedSiteSiteIdSiteSettingsSWebhooksRoute:
      AuthedSiteSiteIdSiteSettingsSWebhooksRoute,
    AuthedSiteSiteIdSiteSettingsSIndexRoute:
      AuthedSiteSiteIdSiteSettingsSIndexRoute,
  }

const AuthedSiteSiteIdSiteSettingsSRouteWithChildren =
  AuthedSiteSiteIdSiteSettingsSRoute._addFileChildren(
    AuthedSiteSiteIdSiteSettingsSRouteChildren,
  )

interface AuthedSiteSiteIdSiteSettingsRouteChildren {
  AuthedSiteSiteIdSiteSettingsSRoute: typeof AuthedSiteSiteIdSiteSettingsSRouteWithChildren
}

const AuthedSiteSiteIdSiteSettingsRouteChildren: AuthedSiteSiteIdSiteSettingsRouteChildren =
  {
    AuthedSiteSiteIdSiteSettingsSRoute:
      AuthedSiteSiteIdSiteSettingsSRouteWithChildren,
  }

const AuthedSiteSiteIdSiteSettingsRouteWithChildren =
  AuthedSiteSiteIdSiteSettingsRoute._addFileChildren(
    AuthedSiteSiteIdSiteSettingsRouteChildren,
  )

interface AuthedSiteSiteIdSiteRouteChildren {
  AuthedSiteSiteIdSiteAnalyticsRoute: typeof AuthedSiteSiteIdSiteAnalyticsRoute
  AuthedSiteSiteIdSiteDeploymentsRoute: typeof AuthedSiteSiteIdSiteDeploymentsRoute
  AuthedSiteSiteIdSiteIndexRoute: typeof AuthedSiteSiteIdSiteIndexRoute
  AuthedSiteSiteIdSiteSettingsRoute: typeof AuthedSiteSiteIdSiteSettingsRouteWithChildren
  AuthedSiteSiteIdSiteDeploymentDeploymentIdIndexRoute: typeof AuthedSiteSiteIdSiteDeploymentDeploymentIdIndexRoute
}

const AuthedSiteSiteIdSiteRouteChildren: AuthedSiteSiteIdSiteRouteChildren = {
  AuthedSiteSiteIdSiteAnalyticsRoute: AuthedSiteSiteIdSiteAnalyticsRoute,
  AuthedSiteSiteIdSiteDeploymentsRoute: AuthedSiteSiteIdSiteDeploymentsRoute,
  AuthedSiteSiteIdSiteIndexRoute: AuthedSiteSiteIdSiteIndexRoute,
  AuthedSiteSiteIdSiteSettingsRoute:
    AuthedSiteSiteIdSiteSettingsRouteWithChildren,
  AuthedSiteSiteIdSiteDeploymentDeploymentIdIndexRoute:
    AuthedSiteSiteIdSiteDeploymentDeploymentIdIndexRoute,
}

const AuthedSiteSiteIdSiteRouteWithChildren =
  AuthedSiteSiteIdSiteRoute._addFileChildren(AuthedSiteSiteIdSiteRouteChildren)

interface AuthedSiteSiteIdRouteChildren {
  AuthedSiteSiteIdSiteRoute: typeof AuthedSiteSiteIdSiteRouteWithChildren
}

const AuthedSiteSiteIdRouteChildren: AuthedSiteSiteIdRouteChildren = {
  AuthedSiteSiteIdSiteRoute: AuthedSiteSiteIdSiteRouteWithChildren,
}

const AuthedSiteSiteIdRouteWithChildren =
  AuthedSiteSiteIdRoute._addFileChildren(AuthedSiteSiteIdRouteChildren)

interface AuthedTeamTeamIdSettingsSRouteChildren {
  AuthedTeamTeamIdSettingsSActionsRoute: typeof AuthedTeamTeamIdSettingsSActionsRoute
  AuthedTeamTeamIdSettingsSCiRoute: typeof AuthedTeamTeamIdSettingsSCiRoute
  AuthedTeamTeamIdSettingsSKeysRoute: typeof AuthedTeamTeamIdSettingsSKeysRoute
  AuthedTeamTeamIdSettingsSMembersRoute: typeof AuthedTeamTeamIdSettingsSMembersRoute
  AuthedTeamTeamIdSettingsSTransferRoute: typeof AuthedTeamTeamIdSettingsSTransferRoute
  AuthedTeamTeamIdSettingsSWebhooksRoute: typeof AuthedTeamTeamIdSettingsSWebhooksRoute
  AuthedTeamTeamIdSettingsSIndexRoute: typeof AuthedTeamTeamIdSettingsSIndexRoute
}

const AuthedTeamTeamIdSettingsSRouteChildren: AuthedTeamTeamIdSettingsSRouteChildren =
  {
    AuthedTeamTeamIdSettingsSActionsRoute:
      AuthedTeamTeamIdSettingsSActionsRoute,
    AuthedTeamTeamIdSettingsSCiRoute: AuthedTeamTeamIdSettingsSCiRoute,
    AuthedTeamTeamIdSettingsSKeysRoute: AuthedTeamTeamIdSettingsSKeysRoute,
    AuthedTeamTeamIdSettingsSMembersRoute:
      AuthedTeamTeamIdSettingsSMembersRoute,
    AuthedTeamTeamIdSettingsSTransferRoute:
      AuthedTeamTeamIdSettingsSTransferRoute,
    AuthedTeamTeamIdSettingsSWebhooksRoute:
      AuthedTeamTeamIdSettingsSWebhooksRoute,
    AuthedTeamTeamIdSettingsSIndexRoute: AuthedTeamTeamIdSettingsSIndexRoute,
  }

const AuthedTeamTeamIdSettingsSRouteWithChildren =
  AuthedTeamTeamIdSettingsSRoute._addFileChildren(
    AuthedTeamTeamIdSettingsSRouteChildren,
  )

interface AuthedTeamTeamIdSettingsRouteChildren {
  AuthedTeamTeamIdSettingsSRoute: typeof AuthedTeamTeamIdSettingsSRouteWithChildren
}

const AuthedTeamTeamIdSettingsRouteChildren: AuthedTeamTeamIdSettingsRouteChildren =
  {
    AuthedTeamTeamIdSettingsSRoute: AuthedTeamTeamIdSettingsSRouteWithChildren,
  }

const AuthedTeamTeamIdSettingsRouteWithChildren =
  AuthedTeamTeamIdSettingsRoute._addFileChildren(
    AuthedTeamTeamIdSettingsRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedSiteNewRoute: typeof AuthedSiteNewRoute
  AuthedTeamNewRoute: typeof AuthedTeamNewRoute
  AuthedSiteSiteIdRoute: typeof AuthedSiteSiteIdRouteWithChildren
  AuthedTeamTeamIdSitesRoute: typeof AuthedTeamTeamIdSitesRoute
  AuthedTeamTeamIdIndexRoute: typeof AuthedTeamTeamIdIndexRoute
  AuthedTeamTeamIdSettingsRoute: typeof AuthedTeamTeamIdSettingsRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedSiteNewRoute: AuthedSiteNewRoute,
  AuthedTeamNewRoute: AuthedTeamNewRoute,
  AuthedSiteSiteIdRoute: AuthedSiteSiteIdRouteWithChildren,
  AuthedTeamTeamIdSitesRoute: AuthedTeamTeamIdSitesRoute,
  AuthedTeamTeamIdIndexRoute: AuthedTeamTeamIdIndexRoute,
  AuthedTeamTeamIdSettingsRoute: AuthedTeamTeamIdSettingsRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthedRouteWithChildren
  '/bootstrap': typeof BootstrapRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/admin': typeof AuthedAdminARouteWithChildren
  '/settings': typeof AuthedSettingsSRouteWithChildren
  '/site/new': typeof AuthedSiteNewRoute
  '/team/new': typeof AuthedTeamNewRoute
  '/invite/$inviteId': typeof InviteInviteIdIndexRoute
  '/site/$siteId': typeof AuthedSiteSiteIdSiteRouteWithChildren
  '/team/$teamId/sites': typeof AuthedTeamTeamIdSitesRoute
  '/admin/': typeof AuthedAdminAIndexRoute
  '/settings/': typeof AuthedSettingsSIndexRoute
  '/team/$teamId': typeof AuthedTeamTeamIdIndexRoute
  '/site/$siteId/analytics': typeof AuthedSiteSiteIdSiteAnalyticsRoute
  '/site/$siteId/deployments': typeof AuthedSiteSiteIdSiteDeploymentsRoute
  '/team/$teamId/settings': typeof AuthedTeamTeamIdSettingsSRouteWithChildren
  '/site/$siteId/': typeof AuthedSiteSiteIdSiteIndexRoute
  '/site/$siteId/settings': typeof AuthedSiteSiteIdSiteSettingsSRouteWithChildren
  '/team/$teamId/settings/actions': typeof AuthedTeamTeamIdSettingsSActionsRoute
  '/team/$teamId/settings/ci': typeof AuthedTeamTeamIdSettingsSCiRoute
  '/team/$teamId/settings/keys': typeof AuthedTeamTeamIdSettingsSKeysRoute
  '/team/$teamId/settings/members': typeof AuthedTeamTeamIdSettingsSMembersRoute
  '/team/$teamId/settings/transfer': typeof AuthedTeamTeamIdSettingsSTransferRoute
  '/team/$teamId/settings/webhooks': typeof AuthedTeamTeamIdSettingsSWebhooksRoute
  '/team/$teamId/settings/': typeof AuthedTeamTeamIdSettingsSIndexRoute
  '/site/$siteId/settings/actions': typeof AuthedSiteSiteIdSiteSettingsSActionsRoute
  '/site/$siteId/settings/ci': typeof AuthedSiteSiteIdSiteSettingsSCiRoute
  '/site/$siteId/settings/domains': typeof AuthedSiteSiteIdSiteSettingsSDomainsRoute
  '/site/$siteId/settings/ipfs': typeof AuthedSiteSiteIdSiteSettingsSIpfsRoute
  '/site/$siteId/settings/keys': typeof AuthedSiteSiteIdSiteSettingsSKeysRoute
  '/site/$siteId/settings/rules': typeof AuthedSiteSiteIdSiteSettingsSRulesRoute
  '/site/$siteId/settings/transfer': typeof AuthedSiteSiteIdSiteSettingsSTransferRoute
  '/site/$siteId/settings/webhooks': typeof AuthedSiteSiteIdSiteSettingsSWebhooksRoute
  '/site/$siteId/deployment/$deploymentId': typeof AuthedSiteSiteIdSiteDeploymentDeploymentIdIndexRoute
  '/site/$siteId/settings/': typeof AuthedSiteSiteIdSiteSettingsSIndexRoute
}

export interface FileRoutesByTo {
  '/bootstrap': typeof BootstrapRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/admin': typeof AuthedAdminAIndexRoute
  '/settings': typeof AuthedSettingsSIndexRoute
  '/site/new': typeof AuthedSiteNewRoute
  '/team/new': typeof AuthedTeamNewRoute
  '/invite/$inviteId': typeof InviteInviteIdIndexRoute
  '/site/$siteId': typeof AuthedSiteSiteIdSiteIndexRoute
  '/team/$teamId/sites': typeof AuthedTeamTeamIdSitesRoute
  '/team/$teamId': typeof AuthedTeamTeamIdIndexRoute
  '/site/$siteId/analytics': typeof AuthedSiteSiteIdSiteAnalyticsRoute
  '/site/$siteId/deployments': typeof AuthedSiteSiteIdSiteDeploymentsRoute
  '/team/$teamId/settings': typeof AuthedTeamTeamIdSettingsSIndexRoute
  '/site/$siteId/settings': typeof AuthedSiteSiteIdSiteSettingsSIndexRoute
  '/team/$teamId/settings/actions': typeof AuthedTeamTeamIdSettingsSActionsRoute
  '/team/$teamId/settings/ci': typeof AuthedTeamTeamIdSettingsSCiRoute
  '/team/$teamId/settings/keys': typeof AuthedTeamTeamIdSettingsSKeysRoute
  '/team/$teamId/settings/members': typeof AuthedTeamTeamIdSettingsSMembersRoute
  '/team/$teamId/settings/transfer': typeof AuthedTeamTeamIdSettingsSTransferRoute
  '/team/$teamId/settings/webhooks': typeof AuthedTeamTeamIdSettingsSWebhooksRoute
  '/site/$siteId/settings/actions': typeof AuthedSiteSiteIdSiteSettingsSActionsRoute
  '/site/$siteId/settings/ci': typeof AuthedSiteSiteIdSiteSettingsSCiRoute
  '/site/$siteId/settings/domains': typeof AuthedSiteSiteIdSiteSettingsSDomainsRoute
  '/site/$siteId/settings/ipfs': typeof AuthedSiteSiteIdSiteSettingsSIpfsRoute
  '/site/$siteId/settings/keys': typeof AuthedSiteSiteIdSiteSettingsSKeysRoute
  '/site/$siteId/settings/rules': typeof AuthedSiteSiteIdSiteSettingsSRulesRoute
  '/site/$siteId/settings/transfer': typeof AuthedSiteSiteIdSiteSettingsSTransferRoute
  '/site/$siteId/settings/webhooks': typeof AuthedSiteSiteIdSiteSettingsSWebhooksRoute
  '/site/$siteId/deployment/$deploymentId': typeof AuthedSiteSiteIdSiteDeploymentDeploymentIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/bootstrap': typeof BootstrapRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/admin/_a': typeof AuthedAdminARouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/settings/_s': typeof AuthedSettingsSRouteWithChildren
  '/_authed/site/new': typeof AuthedSiteNewRoute
  '/_authed/team/new': typeof AuthedTeamNewRoute
  '/invite/$inviteId/': typeof InviteInviteIdIndexRoute
  '/_authed/site/$siteId': typeof AuthedSiteSiteIdRouteWithChildren
  '/_authed/site/$siteId/_site': typeof AuthedSiteSiteIdSiteRouteWithChildren
  '/_authed/team/$teamId/sites': typeof AuthedTeamTeamIdSitesRoute
  '/_authed/admin/_a/': typeof AuthedAdminAIndexRoute
  '/_authed/settings/_s/': typeof AuthedSettingsSIndexRoute
  '/_authed/team/$teamId/': typeof AuthedTeamTeamIdIndexRoute
  '/_authed/site/$siteId/_site/analytics': typeof AuthedSiteSiteIdSiteAnalyticsRoute
  '/_authed/site/$siteId/_site/deployments': typeof AuthedSiteSiteIdSiteDeploymentsRoute
  '/_authed/team/$teamId/settings': typeof AuthedTeamTeamIdSettingsRouteWithChildren
  '/_authed/team/$teamId/settings/_s': typeof AuthedTeamTeamIdSettingsSRouteWithChildren
  '/_authed/site/$siteId/_site/': typeof AuthedSiteSiteIdSiteIndexRoute
  '/_authed/site/$siteId/_site/settings': typeof AuthedSiteSiteIdSiteSettingsRouteWithChildren
  '/_authed/site/$siteId/_site/settings/_s': typeof AuthedSiteSiteIdSiteSettingsSRouteWithChildren
  '/_authed/team/$teamId/settings/_s/actions': typeof AuthedTeamTeamIdSettingsSActionsRoute
  '/_authed/team/$teamId/settings/_s/ci': typeof AuthedTeamTeamIdSettingsSCiRoute
  '/_authed/team/$teamId/settings/_s/keys': typeof AuthedTeamTeamIdSettingsSKeysRoute
  '/_authed/team/$teamId/settings/_s/members': typeof AuthedTeamTeamIdSettingsSMembersRoute
  '/_authed/team/$teamId/settings/_s/transfer': typeof AuthedTeamTeamIdSettingsSTransferRoute
  '/_authed/team/$teamId/settings/_s/webhooks': typeof AuthedTeamTeamIdSettingsSWebhooksRoute
  '/_authed/team/$teamId/settings/_s/': typeof AuthedTeamTeamIdSettingsSIndexRoute
  '/_authed/site/$siteId/_site/settings/_s/actions': typeof AuthedSiteSiteIdSiteSettingsSActionsRoute
  '/_authed/site/$siteId/_site/settings/_s/ci': typeof AuthedSiteSiteIdSiteSettingsSCiRoute
  '/_authed/site/$siteId/_site/settings/_s/domains': typeof AuthedSiteSiteIdSiteSettingsSDomainsRoute
  '/_authed/site/$siteId/_site/settings/_s/ipfs': typeof AuthedSiteSiteIdSiteSettingsSIpfsRoute
  '/_authed/site/$siteId/_site/settings/_s/keys': typeof AuthedSiteSiteIdSiteSettingsSKeysRoute
  '/_authed/site/$siteId/_site/settings/_s/rules': typeof AuthedSiteSiteIdSiteSettingsSRulesRoute
  '/_authed/site/$siteId/_site/settings/_s/transfer': typeof AuthedSiteSiteIdSiteSettingsSTransferRoute
  '/_authed/site/$siteId/_site/settings/_s/webhooks': typeof AuthedSiteSiteIdSiteSettingsSWebhooksRoute
  '/_authed/site/$siteId/_site/deployment/$deploymentId/': typeof AuthedSiteSiteIdSiteDeploymentDeploymentIdIndexRoute
  '/_authed/site/$siteId/_site/settings/_s/': typeof AuthedSiteSiteIdSiteSettingsSIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/bootstrap'
    | '/debug'
    | '/login'
    | '/'
    | '/admin'
    | '/settings'
    | '/site/new'
    | '/team/new'
    | '/invite/$inviteId'
    | '/site/$siteId'
    | '/team/$teamId/sites'
    | '/admin/'
    | '/settings/'
    | '/team/$teamId'
    | '/site/$siteId/analytics'
    | '/site/$siteId/deployments'
    | '/team/$teamId/settings'
    | '/site/$siteId/'
    | '/site/$siteId/settings'
    | '/team/$teamId/settings/actions'
    | '/team/$teamId/settings/ci'
    | '/team/$teamId/settings/keys'
    | '/team/$teamId/settings/members'
    | '/team/$teamId/settings/transfer'
    | '/team/$teamId/settings/webhooks'
    | '/team/$teamId/settings/'
    | '/site/$siteId/settings/actions'
    | '/site/$siteId/settings/ci'
    | '/site/$siteId/settings/domains'
    | '/site/$siteId/settings/ipfs'
    | '/site/$siteId/settings/keys'
    | '/site/$siteId/settings/rules'
    | '/site/$siteId/settings/transfer'
    | '/site/$siteId/settings/webhooks'
    | '/site/$siteId/deployment/$deploymentId'
    | '/site/$siteId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bootstrap'
    | '/debug'
    | '/login'
    | '/'
    | '/admin'
    | '/settings'
    | '/site/new'
    | '/team/new'
    | '/invite/$inviteId'
    | '/site/$siteId'
    | '/team/$teamId/sites'
    | '/team/$teamId'
    | '/site/$siteId/analytics'
    | '/site/$siteId/deployments'
    | '/team/$teamId/settings'
    | '/site/$siteId/settings'
    | '/team/$teamId/settings/actions'
    | '/team/$teamId/settings/ci'
    | '/team/$teamId/settings/keys'
    | '/team/$teamId/settings/members'
    | '/team/$teamId/settings/transfer'
    | '/team/$teamId/settings/webhooks'
    | '/site/$siteId/settings/actions'
    | '/site/$siteId/settings/ci'
    | '/site/$siteId/settings/domains'
    | '/site/$siteId/settings/ipfs'
    | '/site/$siteId/settings/keys'
    | '/site/$siteId/settings/rules'
    | '/site/$siteId/settings/transfer'
    | '/site/$siteId/settings/webhooks'
    | '/site/$siteId/deployment/$deploymentId'
  id:
    | '__root__'
    | '/_authed'
    | '/bootstrap'
    | '/debug'
    | '/login'
    | '/_authed/'
    | '/_authed/admin'
    | '/_authed/admin/_a'
    | '/_authed/settings'
    | '/_authed/settings/_s'
    | '/_authed/site/new'
    | '/_authed/team/new'
    | '/invite/$inviteId/'
    | '/_authed/site/$siteId'
    | '/_authed/site/$siteId/_site'
    | '/_authed/team/$teamId/sites'
    | '/_authed/admin/_a/'
    | '/_authed/settings/_s/'
    | '/_authed/team/$teamId/'
    | '/_authed/site/$siteId/_site/analytics'
    | '/_authed/site/$siteId/_site/deployments'
    | '/_authed/team/$teamId/settings'
    | '/_authed/team/$teamId/settings/_s'
    | '/_authed/site/$siteId/_site/'
    | '/_authed/site/$siteId/_site/settings'
    | '/_authed/site/$siteId/_site/settings/_s'
    | '/_authed/team/$teamId/settings/_s/actions'
    | '/_authed/team/$teamId/settings/_s/ci'
    | '/_authed/team/$teamId/settings/_s/keys'
    | '/_authed/team/$teamId/settings/_s/members'
    | '/_authed/team/$teamId/settings/_s/transfer'
    | '/_authed/team/$teamId/settings/_s/webhooks'
    | '/_authed/team/$teamId/settings/_s/'
    | '/_authed/site/$siteId/_site/settings/_s/actions'
    | '/_authed/site/$siteId/_site/settings/_s/ci'
    | '/_authed/site/$siteId/_site/settings/_s/domains'
    | '/_authed/site/$siteId/_site/settings/_s/ipfs'
    | '/_authed/site/$siteId/_site/settings/_s/keys'
    | '/_authed/site/$siteId/_site/settings/_s/rules'
    | '/_authed/site/$siteId/_site/settings/_s/transfer'
    | '/_authed/site/$siteId/_site/settings/_s/webhooks'
    | '/_authed/site/$siteId/_site/deployment/$deploymentId/'
    | '/_authed/site/$siteId/_site/settings/_s/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  BootstrapRoute: typeof BootstrapRoute
  DebugRoute: typeof DebugRoute
  LoginRoute: typeof LoginRoute
  InviteInviteIdIndexRoute: typeof InviteInviteIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  BootstrapRoute: BootstrapRoute,
  DebugRoute: DebugRoute,
  LoginRoute: LoginRoute,
  InviteInviteIdIndexRoute: InviteInviteIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authed",
        "/bootstrap",
        "/debug",
        "/login",
        "/invite/$inviteId/"
      ]
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/",
        "/_authed/admin",
        "/_authed/settings",
        "/_authed/site/new",
        "/_authed/team/new",
        "/_authed/site/$siteId",
        "/_authed/team/$teamId/sites",
        "/_authed/team/$teamId/",
        "/_authed/team/$teamId/settings"
      ]
    },
    "/bootstrap": {
      "filePath": "bootstrap.tsx"
    },
    "/debug": {
      "filePath": "debug.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authed/": {
      "filePath": "_authed/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/admin": {
      "filePath": "_authed/admin",
      "parent": "/_authed",
      "children": [
        "/_authed/admin/_a"
      ]
    },
    "/_authed/admin/_a": {
      "filePath": "_authed/admin/_a.tsx",
      "parent": "/_authed/admin",
      "children": [
        "/_authed/admin/_a/"
      ]
    },
    "/_authed/settings": {
      "filePath": "_authed/settings",
      "parent": "/_authed",
      "children": [
        "/_authed/settings/_s"
      ]
    },
    "/_authed/settings/_s": {
      "filePath": "_authed/settings/_s.tsx",
      "parent": "/_authed/settings",
      "children": [
        "/_authed/settings/_s/"
      ]
    },
    "/_authed/site/new": {
      "filePath": "_authed/site/new.tsx",
      "parent": "/_authed"
    },
    "/_authed/team/new": {
      "filePath": "_authed/team/new.tsx",
      "parent": "/_authed"
    },
    "/invite/$inviteId/": {
      "filePath": "invite/$inviteId/index.tsx"
    },
    "/_authed/site/$siteId": {
      "filePath": "_authed/site",
      "parent": "/_authed",
      "children": [
        "/_authed/site/$siteId/_site"
      ]
    },
    "/_authed/site/$siteId/_site": {
      "filePath": "_authed/site/$siteId._site.tsx",
      "parent": "/_authed/site/$siteId",
      "children": [
        "/_authed/site/$siteId/_site/analytics",
        "/_authed/site/$siteId/_site/deployments",
        "/_authed/site/$siteId/_site/",
        "/_authed/site/$siteId/_site/settings",
        "/_authed/site/$siteId/_site/deployment/$deploymentId/"
      ]
    },
    "/_authed/team/$teamId/sites": {
      "filePath": "_authed/team/$teamId/sites.tsx",
      "parent": "/_authed"
    },
    "/_authed/admin/_a/": {
      "filePath": "_authed/admin/_a/index.tsx",
      "parent": "/_authed/admin/_a"
    },
    "/_authed/settings/_s/": {
      "filePath": "_authed/settings/_s.index.tsx",
      "parent": "/_authed/settings/_s"
    },
    "/_authed/team/$teamId/": {
      "filePath": "_authed/team/$teamId/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/site/$siteId/_site/analytics": {
      "filePath": "_authed/site/$siteId._site/analytics.tsx",
      "parent": "/_authed/site/$siteId/_site"
    },
    "/_authed/site/$siteId/_site/deployments": {
      "filePath": "_authed/site/$siteId._site/deployments.tsx",
      "parent": "/_authed/site/$siteId/_site"
    },
    "/_authed/team/$teamId/settings": {
      "filePath": "_authed/team/$teamId/settings",
      "parent": "/_authed",
      "children": [
        "/_authed/team/$teamId/settings/_s"
      ]
    },
    "/_authed/team/$teamId/settings/_s": {
      "filePath": "_authed/team/$teamId/settings/_s.tsx",
      "parent": "/_authed/team/$teamId/settings",
      "children": [
        "/_authed/team/$teamId/settings/_s/actions",
        "/_authed/team/$teamId/settings/_s/ci",
        "/_authed/team/$teamId/settings/_s/keys",
        "/_authed/team/$teamId/settings/_s/members",
        "/_authed/team/$teamId/settings/_s/transfer",
        "/_authed/team/$teamId/settings/_s/webhooks",
        "/_authed/team/$teamId/settings/_s/"
      ]
    },
    "/_authed/site/$siteId/_site/": {
      "filePath": "_authed/site/$siteId._site/index.tsx",
      "parent": "/_authed/site/$siteId/_site"
    },
    "/_authed/site/$siteId/_site/settings": {
      "filePath": "_authed/site/$siteId._site/settings",
      "parent": "/_authed/site/$siteId/_site",
      "children": [
        "/_authed/site/$siteId/_site/settings/_s"
      ]
    },
    "/_authed/site/$siteId/_site/settings/_s": {
      "filePath": "_authed/site/$siteId._site/settings/_s.tsx",
      "parent": "/_authed/site/$siteId/_site/settings",
      "children": [
        "/_authed/site/$siteId/_site/settings/_s/actions",
        "/_authed/site/$siteId/_site/settings/_s/ci",
        "/_authed/site/$siteId/_site/settings/_s/domains",
        "/_authed/site/$siteId/_site/settings/_s/ipfs",
        "/_authed/site/$siteId/_site/settings/_s/keys",
        "/_authed/site/$siteId/_site/settings/_s/rules",
        "/_authed/site/$siteId/_site/settings/_s/transfer",
        "/_authed/site/$siteId/_site/settings/_s/webhooks",
        "/_authed/site/$siteId/_site/settings/_s/"
      ]
    },
    "/_authed/team/$teamId/settings/_s/actions": {
      "filePath": "_authed/team/$teamId/settings/_s.actions.tsx",
      "parent": "/_authed/team/$teamId/settings/_s"
    },
    "/_authed/team/$teamId/settings/_s/ci": {
      "filePath": "_authed/team/$teamId/settings/_s.ci.tsx",
      "parent": "/_authed/team/$teamId/settings/_s"
    },
    "/_authed/team/$teamId/settings/_s/keys": {
      "filePath": "_authed/team/$teamId/settings/_s.keys.tsx",
      "parent": "/_authed/team/$teamId/settings/_s"
    },
    "/_authed/team/$teamId/settings/_s/members": {
      "filePath": "_authed/team/$teamId/settings/_s.members.tsx",
      "parent": "/_authed/team/$teamId/settings/_s"
    },
    "/_authed/team/$teamId/settings/_s/transfer": {
      "filePath": "_authed/team/$teamId/settings/_s.transfer.tsx",
      "parent": "/_authed/team/$teamId/settings/_s"
    },
    "/_authed/team/$teamId/settings/_s/webhooks": {
      "filePath": "_authed/team/$teamId/settings/_s.webhooks.tsx",
      "parent": "/_authed/team/$teamId/settings/_s"
    },
    "/_authed/team/$teamId/settings/_s/": {
      "filePath": "_authed/team/$teamId/settings/_s.index.tsx",
      "parent": "/_authed/team/$teamId/settings/_s"
    },
    "/_authed/site/$siteId/_site/settings/_s/actions": {
      "filePath": "_authed/site/$siteId._site/settings/_s.actions.tsx",
      "parent": "/_authed/site/$siteId/_site/settings/_s"
    },
    "/_authed/site/$siteId/_site/settings/_s/ci": {
      "filePath": "_authed/site/$siteId._site/settings/_s.ci.tsx",
      "parent": "/_authed/site/$siteId/_site/settings/_s"
    },
    "/_authed/site/$siteId/_site/settings/_s/domains": {
      "filePath": "_authed/site/$siteId._site/settings/_s.domains.tsx",
      "parent": "/_authed/site/$siteId/_site/settings/_s"
    },
    "/_authed/site/$siteId/_site/settings/_s/ipfs": {
      "filePath": "_authed/site/$siteId._site/settings/_s.ipfs.tsx",
      "parent": "/_authed/site/$siteId/_site/settings/_s"
    },
    "/_authed/site/$siteId/_site/settings/_s/keys": {
      "filePath": "_authed/site/$siteId._site/settings/_s.keys.tsx",
      "parent": "/_authed/site/$siteId/_site/settings/_s"
    },
    "/_authed/site/$siteId/_site/settings/_s/rules": {
      "filePath": "_authed/site/$siteId._site/settings/_s.rules.tsx",
      "parent": "/_authed/site/$siteId/_site/settings/_s"
    },
    "/_authed/site/$siteId/_site/settings/_s/transfer": {
      "filePath": "_authed/site/$siteId._site/settings/_s.transfer.tsx",
      "parent": "/_authed/site/$siteId/_site/settings/_s"
    },
    "/_authed/site/$siteId/_site/settings/_s/webhooks": {
      "filePath": "_authed/site/$siteId._site/settings/_s.webhooks.tsx",
      "parent": "/_authed/site/$siteId/_site/settings/_s"
    },
    "/_authed/site/$siteId/_site/deployment/$deploymentId/": {
      "filePath": "_authed/site/$siteId._site/deployment/$deploymentId/index.tsx",
      "parent": "/_authed/site/$siteId/_site"
    },
    "/_authed/site/$siteId/_site/settings/_s/": {
      "filePath": "_authed/site/$siteId._site/settings/_s.index.tsx",
      "parent": "/_authed/site/$siteId/_site/settings/_s"
    }
  }
}
ROUTE_MANIFEST_END */
