name: Build IPFS Cart Docker Image

on:
    push:
        branches: [master]
        paths:
            - "services/ipfs-cart/**"
    workflow_dispatch: # Allows manual triggering

jobs:
    build-docker:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./services/ipfs-cart
                  file: ./services/ipfs-cart/Dockerfile
                  push: true
                  tags: ghcr.io/v3xlabs/ipfs-cart:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
